import fs from 'node:fs';
import { e2bRunShell } from './tools.js';
import { isRetiredMarket } from './retired-markets.js';
// The caller supplies an explicit permitted origin and selectors. No page script can
// change the allowed origin or authorize a purchase, identity check or subscription.
export async function browserAction(args,env,signal,sandboxSession){
 let u;try{u=new URL(args.url);}catch{return{ok:false,error:'invalid_browser_url'};}
 if(u.protocol!=='https:'||u.username||u.password||!u.hostname.includes('.')||/^(localhost|127\.|10\.|192\.168\.|169\.254\.|0\.|\[|172\.(1[6-9]|2\d|3[01])\.)/.test(u.hostname)||isRetiredMarket(u.href))return{ok:false,error:'browser_origin_blocked'};
 if(!sandboxSession)return{ok:false,error:'job_sandbox_required'};
 if(!Array.isArray(args.steps)||args.steps.length>20)return{ok:false,error:'bounded_browser_steps_required'};
 const actions=new Set(['click','type','select','upload','wait','extract','screenshot']);
 if(args.steps.some(s=>!actions.has(s.action)||typeof s.selector!=='string'&&s.action!=='screenshot'))return{ok:false,error:'invalid_browser_action'};
 const runner=`const fs=require('node:fs');const path=require('node:path');const {launchBrowser}=require('/home/user/autonomos-browser.cjs');(async()=>{const request=JSON.parse(fs.readFileSync('/home/user/browser-action.json','utf8'));const origin=new URL(request.url).origin;const browser=await launchBrowser();try{const stateFile='/home/user/browser-session.json';const context=await browser.newContext(fs.existsSync(stateFile)?{storageState:stateFile}:{});await context.route('**/*',async route=>{const r=route.request();if(r.isNavigationRequest()&&r.frame()===page.mainFrame()&&new URL(r.url()).origin!==origin)return route.abort();return route.continue();});const page=await context.newPage();await page.goto(request.url,{waitUntil:'domcontentloaded',timeout:25000});const results=[];for(const step of request.steps){const text=await page.locator('body').innerText();if(/verify you are human|complete the captcha|government id|enter (?:the )?(?:2fa|verification code)|confirm purchase|subscribe now/i.test(text))throw Error('OWNER_ACTION_REQUIRED');const target=step.selector?page.locator(step.selector):null;switch(step.action){case'type':await target.fill(String(step.value||''));break;case'click':await target.click({timeout:10000});break;case'select':await target.selectOption(String(step.value||''));break;case'upload':{const file=path.resolve('/home/user',String(step.value||''));if(!file.startsWith('/home/user/')||file.endsWith('browser-session.json'))throw Error('invalid_upload_path');await target.setInputFiles(file);break;}case'wait':await target.waitFor({state:'visible',timeout:10000});break;case'extract':results.push({selector:step.selector,text:(await target.innerText()).slice(0,4000)});break;case'screenshot':await page.screenshot({path:'/home/user/browser-evidence.png'});break;}if(new URL(page.url()).origin!==origin)throw Error('browser_origin_changed');}await context.storageState({path:stateFile});fs.chmodSync(stateFile,0o600);console.log(JSON.stringify({ok:true,url:page.url(),results,externalConfirmation:results.map(x=>x.text).join('\\n')}));}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});`;
 const r=await e2bRunShell({command:'node /home/user/browser-actions.cjs',files:[{path:'autonomos-browser.cjs',content:fs.readFileSync(new URL('./browser-runtime.cjs',import.meta.url),'utf8')},{path:'browser-actions.cjs',content:runner},{path:'browser-action.json',content:JSON.stringify(args)}],collectPaths:args.steps.some(s=>s.action==='screenshot')?['browser-evidence.png']:[]},env,signal,sandboxSession);
 if(!r.ok)return{...r,uncertain:args.steps.some(s=>s.action==='click')};try{return{...JSON.parse(r.stdout.trim()),artifacts:r.artifacts||[],provider:'current_chromium'};}catch{return{ok:false,error:'browser_action_output_invalid',uncertain:true};}
}
