import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {EventEmitter} from 'node:events';import {Readable} from 'node:stream';import {safeGet} from '../../src/qonvexa/scanner.js';
const resolve=async()=>[{address:'8.8.8.8',family:4}];
function transport(t,responses,inspect=()=>{}){const original=http.get;let calls=0;http.get=(url,options,callback)=>{inspect(url,options);const req=new EventEmitter();req.destroy=error=>{if(error)req.emit('error',error);req.emit('close');};queueMicrotask(()=>{const r=responses[calls++]||responses.at(-1);const stream=Readable.from(r.chunks||[Buffer.from(r.body||'')]);stream.headers=r.headers||{'content-type':'text/html'};stream.statusCode=r.status||200;stream.on('end',()=>req.emit('close'));callback(stream);});return req;};t.after(()=>{http.get=original;});return ()=>calls;}
test('Redirect to metadata rejected before second socket',async t=>{const count=transport(t,[{status:302,headers:{location:'http://169.254.169.254/latest/meta-data/'}}]);await assert.rejects(safeGet('http://example.com',{resolve}),/UNSAFE_URL/);assert.equal(count(),1);});
test('DNS revalidated on each redirect',async t=>{let checks=0;transport(t,[{status:302,headers:{location:'http://other.example.com/'}}]);await assert.rejects(safeGet('http://example.com',{resolve:async()=>++checks===1?[{address:'8.8.8.8',family:4}]:[{address:'10.0.0.1',family:4}]}),/UNSAFE_DNS/);assert.equal(checks,2);});
test('Validated DNS address is pinned to socket lookup',async t=>{let pin;transport(t,[{body:'<h1>ok</h1>'}],(_url,opts)=>opts.lookup('example.com',{},(_err,address)=>pin=address));const r=await safeGet('http://example.com',{resolve});assert.equal(pin,'8.8.8.8');assert.equal(r.status,200);});
test('Byte cap enforced while streaming',async t=>{transport(t,[{chunks:[Buffer.alloc(20),Buffer.alloc(20)]}]);await assert.rejects(safeGet('http://example.com',{resolve,maxBytes:30}),/BYTE_LIMIT/);});
test('Binary downloads blocked',async t=>{transport(t,[{headers:{'content-type':'application/octet-stream'}}]);await assert.rejects(safeGet('http://example.com',{resolve}),/CONTENT_TYPE_BLOCKED/);});
test('Compressed content is not misinterpreted as HTML evidence',async t=>{transport(t,[{headers:{'content-type':'text/html','content-encoding':'gzip'}}]);await assert.rejects(safeGet('http://example.com',{resolve}),/CONTENT_ENCODING_BLOCKED/);});
test('Credential-bearing requests do not follow redirects',async t=>{transport(t,[{status:302,headers:{location:'/next'}}]);await assert.rejects(safeGet('http://example.com',{resolve,headers:{authorization:'fixture'}}),/AUTH_REDIRECT_BLOCKED/);});
test('Crawl same-origin boundary blocks external redirect',async t=>{transport(t,[{status:302,headers:{location:'http://other.example.com'}}]);await assert.rejects(safeGet('http://example.com',{resolve,origin:'http://example.com'}),/CROSS_ORIGIN_REDIRECT/);});
test('Redirect count is bounded',async t=>{const count=transport(t,[{status:302,headers:{location:'/loop'}}]);await assert.rejects(safeGet('http://example.com',{resolve,maxRedirects:2}),/REDIRECT_LIMIT/);assert.equal(count(),3);});
test('DNS timeout is bounded',async()=>{const before=Date.now();await assert.rejects(safeGet('http://example.com',{resolve:()=>new Promise(()=>{}),timeoutMs:20}),/DNS_TIMEOUT/);assert(Date.now()-before<1000);});
